# Generated by Django 4.1.1 on 2022-10-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_customer_sales_contact_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("POTENTIAL", "Potential customer"),
                    ("EXISTING", "Existing customer"),
                ],
                default="POTENTIAL",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
