# Generated by Django 4.1.1 on 2022-10-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_customer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("POTENTIAL", "Potential customer"),
                    ("EXISTING", "Existing customer"),
                ],
                default="POTENTIAL",
                max_length=16,
            ),
        ),
    ]
