# Generated by Django 4.1.1 on 2022-10-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_alter_customer_customer_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="customer_type",
        ),
    ]
