# Generated by Django 4.1.1 on 2022-09-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": (("can_add_customer", "To create Customers"),)},
        ),
    ]
