# Generated by Django 4.1.1 on 2022-10-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SALER", "Saler"),
                    ("GESTION", "Gestion"),
                    ("SUPPORT", "Support"),
                    ("ADMIN", "Admin"),
                ],
                max_length=16,
            ),
        ),
    ]
